language: node_js

os: 
  - linux

arch:
  - amd64

dist:
  - bionic

node_js:
  - "lts/*"

services:
  - mongodb

env:
  - NODE_ENV=travis

before_script:
- npm install

script:
  - npm test

notifications:
  email: false
